session_name: hypertts
start_directory: ./ # load session relative to config location (project root).
shell_command_before:
  - source ${PYTHON_ENV_DIR}/anki-hyper-tts/bin/activate
  - source .bash_aliases
  - source ${SECRETS_DIR}/hypertts/hypertts_tests.sh
  - eval "$(register-python-argcomplete pytest)"
  - clear
windows:
- window_name: hypertts
  focus: true
- window_name: hypertts-3.13
  panes:
    - shell_command: source ${PYTHON_ENV_DIR}/anki-hyper-tts-3.13/bin/activate
- window_name: git
- window_name: ai
- window_name: anki-log
  panes:
    - shell_command: tail -f ${LOGS_DIR}/anki.log
- window_name: log
  panes:
    - shell_command: tail -f ${LOGS_DIR}/hypertts.log
- window_name: secrets
  panes:
    - shell_command: 
      - cd ${SECRETS_DIR}/hypertts
      - clear
#- window_name: python-3.12
#  panes:
#    - shell_command: 
#      - source ${PYTHON_ENV_DIR}/anki-hyper-tts-3.12/bin/activate
#      - clear
